MULTIVAR = set(["AM21B","MATH21B", "MATH23B","MATH25A", "MATH55A"])
LINALG = set(["AM21A","MATH21A", "MATH23A","MATH25B", "MATH55B"])

STAT110 = "STAT110"
CS050 = "CS050"
CS051 = "CS051"
CS061 = "CS061"
CS020 = "CS020"
CS121 = "CS121"
CS124 = "CS124"
CS181 = "CS181"
CS182 = "CS182"
MATH23A = "MATH23A"
MATH25B = "MATH25B"
MATH25A = "MATH25A"
MATH25B = "MATH25B"
MATH55A = "MATH55A"
MATH55B = "MATH55B"

courses = {
'AM106': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '359PM',
           'CLOCKSTART': '230PM',
           'COURSE': 'AM106',
           'DAYS': set(['M', 'W']),
           'END': 1559,
           'ENROLLMENT': 31,
           'PREREQS': [set(['AM21B',
                            'MATH21B',
                            'MATH23B',
                            'MATH25A',
                            'MATH55A']),
                       set(['AM21A',
                            'MATH21A',
                            'MATH23A',
                            'MATH25B',
                            'MATH55B'])],
           'Q': 3.7,
           'SEMESTER': 'F',
           'START': 1430,
           'WORKLOAD': 6.6},
 'AM107': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1129AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'AM107',
           'DAYS': set(['R', 'T']),
           'END': 1129,
           'ENROLLMENT': 23,
           'PREREQS': [],
           'Q': 4.3,
           'SEMESTER': 'S',
           'START': 1000,
           'WORKLOAD': 8.1},
 'AM120': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1129AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'AM120',
           'DAYS': set(['R', 'T']),
           'END': 1129,
           'ENROLLMENT': 108,
           'PREREQS': [set(['AM21B',
                            'MATH21B',
                            'MATH23B',
                            'MATH25A',
                            'MATH55A']),
                       set(['AM21A',
                            'MATH21A',
                            'MATH23A',
                            'MATH25B',
                            'MATH55B']),
                       'CS050'],
           'Q': 4.3,
           'SEMESTER': 'S',
           'START': 1000,
           'WORKLOAD': 6.9},
 'AM121': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '1129AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'AM121',
           'DAYS': set(['M', 'W']),
           'END': 1129,
           'ENROLLMENT': 73,
           'PREREQS': [set(['AM21A',
                            'MATH21A',
                            'MATH23A',
                            'MATH25B',
                            'MATH55B']),
                       'STAT110'],
           'Q': 3.8,
           'SEMESTER': 'F',
           'START': 1000,
           'WORKLOAD': 10.3},
 'AM21A': {'CLOCKDAYS': 'MWF',
           'CLOCKEND': '1159AM',
           'CLOCKSTART': '1100AM',
           'COURSE': 'AM21A',
           'DAYS': set(['F', 'M', 'W']),
           'END': 1159,
           'ENROLLMENT': 169,
           'PREREQS': [],
           'Q': 3.8,
           'SEMESTER': 'F',
           'START': 1100,
           'WORKLOAD': 7.7},
 'AM21B': {'CLOCKDAYS': 'MWF',
           'CLOCKEND': '1159AM',
           'CLOCKSTART': '1100AM',
           'COURSE': 'AM21B',
           'DAYS': set(['F', 'M', 'W']),
           'END': 1159,
           'ENROLLMENT': 79,
           'PREREQS': [set(['AM21A',
                            'MATH21B',
                            'MATH23B',
                            'MATH25A',
                            'MATH55A'])],
           'Q': 3.3,
           'SEMESTER': 'S',
           'START': 1100,
           'WORKLOAD': 9.2},
 'CS001': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1129AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'CS001',
           'DAYS': set(['R', 'T']),
           'END': 1129,
           'ENROLLMENT': 76,
           'PREREQS': [],
           'Q': 3.8,
           'SEMESTER': 'S',
           'START': 1000,
           'WORKLOAD': 7.4},
 'CS020': {'CLOCKDAYS': 'MWF',
           'CLOCKEND': '1059AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'CS020',
           'DAYS': set(['F', 'M', 'W']),
           'END': 1059,
           'ENROLLMENT': 58,
           'PREREQS': [],
           'Q': 4.4,
           'SEMESTER': 'S',
           'START': 1000,
           'WORKLOAD': 5.0},
 'CS050': {'CLOCKDAYS': 'F',
           'CLOCKEND': '1159AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'CS050',
           'DAYS': set(['F']),
           'END': 1159,
           'ENROLLMENT': 750,
           'PREREQS': [],
           'Q': 3.5,
           'SEMESTER': 'F',
           'START': 1000,
           'WORKLOAD': 15.2},
 'CS051': {'CLOCKDAYS': 'T',
           'CLOCKEND': '229PM',
           'CLOCKSTART': '100PM',
           'COURSE': 'CS051',
           'DAYS': set(['T']),
           'END': 1429,
           'ENROLLMENT': 348,
           'PREREQS': ['CS050'],
           'Q': 3.4,
           'SEMESTER': 'S',
           'START': 1300,
           'WORKLOAD': 13.9},
 'CS061': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '359PM',
           'CLOCKSTART': '230PM',
           'COURSE': 'CS061',
           'DAYS': set(['R', 'T']),
           'END': 1559,
           'ENROLLMENT': 129,
           'PREREQS': ['CS050'],
           'Q': 4.2,
           'SEMESTER': 'F',
           'START': 1430,
           'WORKLOAD': 15.8},
 'CS091R': {'CLOCKDAYS': '',
            'CLOCKEND': '',
            'CLOCKSTART': '',
            'COURSE': 'CS091R',
            'DAYS': set([]), 
            'END': -1,
            'ENROLLMENT': 5,
            'PREREQS': [],
            'Q': 3.879545455,
            'SEMESTER': 'F',
            'START': -1,
            'WORKLOAD': 11.04772727},
'CS091R': {'CLOCKDAYS': '',
            'CLOCKEND': '',
            'CLOCKSTART': '',
            'COURSE': 'CS091R',
            'DAYS': set([]), 
            'END': -1,
            'ENROLLMENT': 5,
            'PREREQS': [],
            'Q': 3.879545455,
            'SEMESTER': 'S',
            'START': -1,
            'WORKLOAD': 11.04772727},
 'CS096': {'CLOCKDAYS': 'MWF',
           'CLOCKEND': '559PM',
           'CLOCKSTART': '400PM',
           'COURSE': 'CS096',
           'DAYS': set(['F', 'M', 'W']),
           'END': 1759,
           'ENROLLMENT': 2,
           'PREREQS': [set(['CS051', 'CS061'])],
           'Q': 4.5,
           'SEMESTER': 'F',
           'START': 1600,
           'WORKLOAD': 3.0},
 'CS105': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '229PM',
           'CLOCKSTART': '100PM',
           'COURSE': 'CS105',
           'DAYS': set(['R', 'T']),
           'END': 1429,
           'ENROLLMENT': 37,
           'PREREQS': [],
           'Q': 4.7,
           'SEMESTER': 'F',
           'START': 1300,
           'WORKLOAD': 5.2},
 'CS108': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1259PM',
           'CLOCKSTART': '1130AM',
           'COURSE': 'CS108',
           'DAYS': set(['R', 'T']),
           'END': 1259,
           'ENROLLMENT': 36,
           'PREREQS': [],
           'Q': 4.8,
           'SEMESTER': 'F',
           'START': 1130,
           'WORKLOAD': 4.1},
 'CS109A': {'CLOCKDAYS': 'MW',
            'CLOCKEND': '229PM',
            'CLOCKSTART': '100PM',
            'COURSE': 'CS109A',
            'DAYS': set(['M', 'W']),
            'END': 1429,
            'ENROLLMENT': 131,
            'PREREQS': ['CS050'],
            'Q': 3.1,
            'SEMESTER': 'F',
            'START': 1300,
            'WORKLOAD': 9.1},
 'CS109B': {'CLOCKDAYS': 'MW',
            'CLOCKEND': '229PM',
            'CLOCKSTART': '100PM',
            'COURSE': 'CS109B',
            'DAYS': set(['M', 'W']),
            'END': 1429,
            'ENROLLMENT': 79,
            'PREREQS': ['CS109A'],
            'Q': 3.5,
            'SEMESTER': 'S',
            'START': 1300,
            'WORKLOAD': 11.9},
 'CS121': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1129AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'CS121',
           'DAYS': set(['R', 'T']),
           'END': 1129,
           'ENROLLMENT': 169,
           'PREREQS': [set(['CS020',
                            'MATH23A',
                            'MATH25A',
                            'MATH25B',
                            'MATH55A',
                            'MATH55B'])],
           'Q': 3.2,
           'SEMESTER': 'F',
           'START': 1000,
           'WORKLOAD': 9.5},
 'CS124': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1259PM',
           'CLOCKSTART': '1130AM',
           'COURSE': 'CS124',
           'DAYS': set(['R', 'T']),
           'END': 1259,
           'ENROLLMENT': 217,
           'PREREQS': ['CS121'],
           'Q': 3.9,
           'SEMESTER': 'S',
           'START': 1130,
           'WORKLOAD': 15.2},
 'CS126': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1129AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'CS126',
           'DAYS': set(['R', 'T']),
           'END': 1129,
           'ENROLLMENT': 30,
           'PREREQS': ['STAT110', 'CS124'],
           'Q': 3.0,
           'SEMESTER': 'F',
           'START': 1000,
           'WORKLOAD': 8.0},
 'CS127': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1129AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'CS127',
           'DAYS': set(['R', 'T']),
           'END': 1129,
           'ENROLLMENT': 19,
           'PREREQS': [set(['CS121', 'CS124'])],
           'Q': 4.5,
           'SEMESTER': 'S',
           'START': 1000,
           'WORKLOAD': 12.2},
 'CS134': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '359PM',
           'CLOCKSTART': '230PM',
           'COURSE': 'CS134',
           'DAYS': set(['M', 'W']),
           'END': 1559,
           'ENROLLMENT': 167,
           'PREREQS': ['STAT110',
                       set(['AM21A',
                            'MATH21A',
                            'MATH23A',
                            'MATH25B',
                            'MATH55B']),
                       set(['AM21B',
                            'MATH21B',
                            'MATH23B',
                            'MATH25A',
                            'MATH55A'])],
           'Q': 3.5,
           'SEMESTER': 'F',
           'START': 1430,
           'WORKLOAD': 9.3},
 'CS136': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '1259PM',
           'CLOCKSTART': '1130AM',
           'COURSE': 'CS136',
           'DAYS': set(['M', 'W']),
           'END': 1259,
           'ENROLLMENT': 57,
           'PREREQS': [set(['AM21A',
                            'MATH21A',
                            'MATH23A',
                            'MATH25B',
                            'MATH55B']),
                       'CS051',
                       'STAT110',
                       set(['CS181', 'CS182'])],
           'Q': 4.6,
           'SEMESTER': 'F',
           'START': 1130,
           'WORKLOAD': 9.8},
 'CS141': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '1129AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'CS141',
           'DAYS': set(['M', 'W']),
           'END': 1129,
           'ENROLLMENT': 19,
           'PREREQS': ['CS050'],
           'Q': 4.0,
           'SEMESTER': 'F',
           'START': 1000,
           'WORKLOAD': 10.5},
 'CS143': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '359PM',
           'CLOCKSTART': '230PM',
           'COURSE': 'CS143',
           'DAYS': set(['M', 'W']),
           'END': 1559,
           'ENROLLMENT': 43,
           'PREREQS': ['CS050'],
           'Q': 2.8,
           'SEMESTER': 'F',
           'START': 1430,
           'WORKLOAD': 5.5},
 'CS144R': {'CLOCKDAYS': 'MW',
            'CLOCKEND': '359PM',
            'CLOCKSTART': '230PM',
            'COURSE': 'CS144R',
            'DAYS': set(['M', 'W']),
            'END': 1559,
            'ENROLLMENT': 11,
            'PREREQS': [],
            'Q': 4.2,
            'SEMESTER': 'S',
            'START': 1430,
            'WORKLOAD': 5.2},
  'CS144R': {'CLOCKDAYS': 'MW',
            'CLOCKEND': '359PM',
            'CLOCKSTART': '230PM',
            'COURSE': 'CS144R',
            'DAYS': set(['M', 'W']),
            'END': 1559,
            'ENROLLMENT': 11,
            'PREREQS': [],
            'Q': 4.2,
            'SEMESTER': 'F',
            'START': 1430,
            'WORKLOAD': 5.2},
 'CS148': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1259PM',
           'CLOCKSTART': '1130AM',
           'COURSE': 'CS148',
           'DAYS': set(['R', 'T']),
           'END': 1259,
           'ENROLLMENT': 4,
           'PREREQS': [],
           'Q': 5.0,
           'SEMESTER': 'S',
           'START': 1130,
           'WORKLOAD': 5.7},
 'CS152': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '1129AM',
           'CLOCKSTART': '1000AM',
           'COURSE': 'CS152',
           'DAYS': set(['R', 'T']),
           'END': 1129,
           'ENROLLMENT': 19,
           'PREREQS': ['CS051', 'CS121'],
           'Q': 3.4,
           'SEMESTER': 'S',
           'START': 1000,
           'WORKLOAD': 6.6},
 'CS165': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '529PM',
           'CLOCKSTART': '400PM',
           'COURSE': 'CS165',
           'DAYS': set(['M', 'W']),
           'END': 1729,
           'ENROLLMENT': 32,
           'PREREQS': ['CS051', 'CS061'],
           'Q': 4.5,
           'SEMESTER': 'F',
           'START': 1600,
           'WORKLOAD': 10.5},
 'CS171': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '359PM',
           'CLOCKSTART': '230PM',
           'COURSE': 'CS171',
           'DAYS': set(['R', 'T']),
           'END': 1559,
           'ENROLLMENT': 97,
           'PREREQS': ['CS050'],
           'Q': 3.7,
           'SEMESTER': 'F',
           'START': 1430,
           'WORKLOAD': 9.8},
 'CS175': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '229PM',
           'CLOCKSTART': '100PM',
           'COURSE': 'CS175',
           'DAYS': set(['M', 'W']),
           'END': 1429,
           'ENROLLMENT': 13,
           'PREREQS': [set(['CS051', 'CS061']),
                       set(['AM21A',
                            'MATH21A',
                            'MATH23A',
                            'MATH25B',
                            'MATH55B'])],
           'Q': 4.0,
           'SEMESTER': 'F',
           'START': 1300,
           'WORKLOAD': 9.5},
 'CS179': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '359PM',
           'CLOCKSTART': '230PM',
           'COURSE': 'CS179',
           'DAYS': set(['R', 'T']),
           'END': 1559,
           'ENROLLMENT': 59,
           'PREREQS': ['CS050'],
           'Q': 3.6,
           'SEMESTER': 'S',
           'START': 1430,
           'WORKLOAD': 6.8},
 'CS181': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '1029AM',
           'CLOCKSTART': '900AM',
           'COURSE': 'CS181',
           'DAYS': set(['M', 'W']),
           'END': 1029,
           'ENROLLMENT': 215,
           'PREREQS': ['CS051',
                       'STAT110',
                       set(['AM21B',
                            'MATH21B',
                            'MATH23B',
                            'MATH25A',
                            'MATH55A']),
                       set(['AM21A',
                            'MATH21A',
                            'MATH23A',
                            'MATH25B',
                            'MATH55B'])],
           'Q': 3.6,
           'SEMESTER': 'S',
           'START': 900,
           'WORKLOAD': 16.8},
 'CS182': {'CLOCKDAYS': 'TR',
           'CLOCKEND': '229PM',
           'CLOCKSTART': '100PM',
           'COURSE': 'CS182',
           'DAYS': set(['R', 'T']),
           'END': 1429,
           'ENROLLMENT': 84,
           'PREREQS': ['CS051', 'STAT110'],
           'Q': 3.9,
           'SEMESTER': 'F',
           'START': 1300,
           'WORKLOAD': 7.2},
 'CS189': {'CLOCKDAYS': 'F',
           'CLOCKEND': '359PM',
           'CLOCKSTART': '100PM',
           'COURSE': 'CS189',
           'DAYS': set(['F']),
           'END': 1559,
           'ENROLLMENT': 20,
           'PREREQS': [set(['CS181', 'CS182'])],
           'Q': 3.6,
           'SEMESTER': 'S',
           'START': 1300,
           'WORKLOAD': 13.9},
 'CS191': {'CLOCKDAYS': 'MW',
           'CLOCKEND': '1029AM',
           'CLOCKSTART': '900AM',
           'COURSE': 'CS191',
           'DAYS': set(['M', 'W']),
           'END': 1029,
           'ENROLLMENT': 20,
           'PREREQS': [],
           'Q': 3.0,
           'SEMESTER': 'S',
           'START': 900,
           'WORKLOAD': 8.0},
 'ES50': {'CLOCKDAYS': 'MW',
          'CLOCKEND': '359PM',
          'CLOCKSTART': '230PM',
          'COURSE': 'ES50',
          'DAYS': set(['M', 'W']),
          'END': 1559,
          'ENROLLMENT': 85,
          'PREREQS': [],
          'Q': 3.5,
          'SEMESTER': 'F',
          'START': 1430,
          'WORKLOAD': 6.6},
 'ES52': {'CLOCKDAYS': 'MW',
          'CLOCKEND': '229PM',
          'CLOCKSTART': '100PM',
          'COURSE': 'ES52',
          'DAYS': set(['M', 'W']),
          'END': 1429,
          'ENROLLMENT': 53,
          'PREREQS': [],
          'Q': 3.9,
          'SEMESTER': 'F',
          'START': 1300,
          'WORKLOAD': 9.8},
 'MATH154': {'CLOCKDAYS': 'MWF',
             'CLOCKEND': '1259PM',
             'CLOCKSTART': '1200PM',
             'COURSE': 'MATH154',
             'DAYS': set(['F', 'M', 'W']),
             'END': 1259,
             'ENROLLMENT': 30,
             'PREREQS': [set(['AM21B',
                              'MATH21B',
                              'MATH23B',
                              'MATH25A',
                              'MATH55A']),
                         set(['AM21A',
                              'MATH21A',
                              'MATH23A',
                              'MATH25B',
                              'MATH55B'])],
             'Q': 4.5,
             'SEMESTER': 'S',
             'START': 1200,
             'WORKLOAD': 10.1},
 'MATH21A': {'CLOCKDAYS': '',
             'CLOCKEND': '',
             'CLOCKSTART': '',
             'COURSE': 'MATH21A',
             'DAYS': set([]),
             'END': -1,
             'ENROLLMENT': 237,
             'PREREQS': [],
             'Q': 3.6,
             'SEMESTER': 'FS',
             'START': -1,
             'WORKLOAD': 10.0},
 'MATH21B': {'CLOCKDAYS': '',
             'CLOCKEND': '',
             'CLOCKSTART': '',
             'COURSE': 'MATH21B',
             'DAYS': set([]),
             'END': -1,
             'ENROLLMENT': 320,
             'PREREQS': [],
             'Q': 3.5,
             'SEMESTER': 'FS',
             'START': -1,
             'WORKLOAD': 8.4},
 'MATH23A': {'CLOCKDAYS': 'F',
             'CLOCKEND': '159PM',
             'CLOCKSTART': '100PM',
             'COURSE': 'MATH23A',
             'DAYS': set(['F']),
             'END': 1359,
             'ENROLLMENT': 59,
             'PREREQS': [],
             'Q': 3.4,
             'SEMESTER': 'F',
             'START': 1300,
             'WORKLOAD': 10.5},
 'MATH23B': {'CLOCKDAYS': 'TR',
             'CLOCKEND': '359PM',
             'CLOCKSTART': '230PM',
             'COURSE': 'MATH23B',
             'DAYS': set(['R', 'T']),
             'END': 1559,
             'ENROLLMENT': 59,
             'PREREQS': [set(['MATH23A', 'MATH25A'])],
             'Q': 3.9,
             'SEMESTER': 'S',
             'START': 1430,
             'WORKLOAD': 8.8},
 'MATH25A': {'CLOCKDAYS': 'MWF',
             'CLOCKEND': '1059AM',
             'CLOCKSTART': '1000AM',
             'COURSE': 'MATH25A',
             'DAYS': set(['F', 'M', 'W']),
             'END': 1059,
             'ENROLLMENT': 45,
             'PREREQS': [],
             'Q': 4.6,
             'SEMESTER': 'F',
             'START': 1000,
             'WORKLOAD': 17.1},
 'MATH25B': {'CLOCKDAYS': 'MWF',
             'CLOCKEND': '1059AM',
             'CLOCKSTART': '1000AM',
             'COURSE': 'MATH25B',
             'DAYS': set(['F', 'M', 'W']),
             'END': 1059,
             'ENROLLMENT': 38,
             'PREREQS': [set(['MATH25A','MATH55A'])],
             'Q': 3.9,
             'SEMESTER': 'S',
             'START': 1000,
             'WORKLOAD': 16.3},
 'MATH55A': {'CLOCKDAYS': 'MWF',
             'CLOCKEND': '1159AM',
             'CLOCKSTART': '1100AM',
             'COURSE': 'MATH55A',
             'DAYS': set(['F', 'M', 'W']),
             'END': 1159,
             'ENROLLMENT': 11,
             'PREREQS': [],
             'Q': 3.7,
             'SEMESTER': 'F',
             'START': 1100,
             'WORKLOAD': 30.2},
 'MATH55B': {'CLOCKDAYS': 'MWF',
             'CLOCKEND': '1159AM',
             'CLOCKSTART': '1100AM',
             'COURSE': 'MATH55B',
             'DAYS': set(['F', 'M', 'W']),
             'END': 1159,
             'ENROLLMENT': 12,
             'PREREQS': ['MATH55A'],
             'Q': 4.0,
             'SEMESTER': 'S',
             'START': 1100,
             'WORKLOAD': 45.2},
 'STAT110': {'CLOCKDAYS': 'TR',
             'CLOCKEND': '359PM',
             'CLOCKSTART': '230PM',
             'COURSE': 'STAT110',
             'DAYS': set(['R', 'T']),
             'END': 1559,
             'ENROLLMENT': 444,
             'PREREQS': [set(['AM21B',
                              'MATH21B',
                              'MATH23B',
                              'MATH25A',
                              'MATH55A'])],
             'Q': 4.3,
             'SEMESTER': 'F',
             'START': 1430,
             'WORKLOAD': 10.6},
 }
 # 'STAT121A': {'CLOCKDAYS': 'MW',
 #              'CLOCKEND': '229PM',
 #              'CLOCKSTART': '100PM',
 #              'COURSE': 'STAT121A',
 #              'DAYS': set(['M', 'W']),
 #              'END': 1429,
 #              'ENROLLMENT': 131,
 #              'PREREQS': [],
 #              'Q': 3.1,
 #              'SEMESTER': 'F',
 #              'START': 1300,
 #              'WORKLOAD': 9.1},
 # 'STAT121B': {'CLOCKDAYS': 'MW',
 #              'CLOCKEND': '229PM',
 #              'CLOCKSTART': '100PM',
 #              'COURSE': 'STAT121B',
 #              'DAYS': set(['M', 'W']),
 #              'END': 1429,
 #              'ENROLLMENT': 25,
 #              'PREREQS': [],
 #              'Q': 3.5,
 #              'SEMESTER': 'S',
 #              'START': 1300,
 #              'WORKLOAD': 5}
